### PR TITLE
TDD a controller

### PR DESCRIPTION
**Pull request by darrencauthon**
I said I'd offer an alternative view to testing a controller.  The controller existed so I didn't exactly build this from scratch, but this is how I write many of my controllers.  I don't use the generators... I use tests to drive the generation of the code.  That's TDD.

I think that's where I'm not with the mainstream way of Rails thinking.  I think most agree with you that unit testing controllers is a "waste of time," but... that's TDD.  TDD would mean that we drive our code through tests, and if you're doing it -- you won't have untested code.  You wouldn't have the `redirect_to` method at all because you didn't write a test for the redirection target.  

We talked about confirmation bias on Twitter, and... since I didn't come from a Rails or Ruby background, I'm used to testing in other environments.  And I think in most places, those who practice TDD or "test driven" coding test their code.  There's something about Rails where it's become common to skip testing a lot of code.  And we look at the code and say "well, that's minor, we test the important things" but it takes one tiny error in one spot in the code to blow up the application.

I won't keep you long on this, I just wanted to offer another look at testing Rails.  Most Rails programmers I show this to think I'm crazy, but... my applications are pretty well-tested and they hold up really well.  And I've has to rescue dozens of Rails applications in my career that weren't tested this way, and that were disasters.  :smile:

### CODE REVIEW

**Comment by plicjo** [comment]
Wow, those are some deep tests.

They mostly make sense and add value though!

I really don't understand the stubbing of methods to only return the method though....
`c.stubs(:params).returns params` and `controller.stubs(:todos_path).returns todos_path` feel a bit overkill?

**Comment by darrencauthon** [comment]
Overkill?  Ahh, but how else would I test for the title getting set if I didn't pass it in through params?  I'm stubbing over `params` just to get a hash I can easily work with.

And the `todos_path`, I have to set the object so I can mock against it.  

Hmm... but maybe I don't?  Honestly, I don't use the Rails routing helpers very much.  The base controller is coupled to the implementation, so calling some controller methods (like those that touch params or response or some routing) will throw an error.

But I'll have to give it a try, I think I mock now just by habit! :smiley:

**Comment by plicjo** [comment]
Oh, you're a fan of the pure unit test philosophy (stubbing all the things)?

I always thought it was pretty cool. I have found it tiresome to fully commit to, though.

I find that if I'm `new`ing up a whole bunch of objects to unit test something, then that's a clue that I've got coupling for days! I've felt that warning when taking my unit tests to Stub City and when just using the actual classes the unit test is dependent on.

**Comment by darrencauthon** [comment]
It's not really about "pure unit testing" or mocking/faking/stubbing.

It's more about the Single Responsibility Principle, and the **ability** to do TDD.

Take this controller.  What is `params`?  It looks like a hash, but... with the latest Rails it is a hash with all sorts of different behaviors, and its data is pulled from the request.  

This means that if I were to write a unit test for the controller, I'd have to instantiate the controller within the type of environment where it could pull `params` in the same way.  The only practical way to do that is to process the controller through the entire web request, but think of all of the things that happen during a web request?  If there's an error in the view, or a route, or a filter, my unit test will fail.  And think of all the details it might take to set all of that stuff up!  I'm just trying to write a simple test, and I have to be aware and adjust for every other detail of the application.

I just want to be able to write code that does something.  Simply, and quickly.  If I'm working on the code to create a `Todo`, let me do that... don't thrust all of the user authentication, button clicks, CSS styles, UI guts, etc. on me.  

It's hard to explain in writing, at least this morning :smile: but I think the ability to jump into code at this micro-level is essential to true "test driven" code.  No compromise -- if I can't easily test the method, then there's a problem.  And since The Rails Way code is not really conducive to this, I think there is a big problem with most Rails testing.

The problems really don't hit on examples like this Todo... they hit later, after waves of changes have hit the Rails application.  I've seen Rails apps where the devs were testing at the beginning... but as the changes pile up, changes that require micro-level details... they eventually give on testing.  I mean, imagine -- a controller action jumps from 2 lines to 3 lines to 5 lines to 10 lines... then they have to stick in an "if" statement to do 3 more things in this one situation.  They're not doing TDD, they're doing test-after and UGH it's a pain and, hmm, maybe testing isn't worth this pain?  They're right -- testing isn't worth that pain -- but they never question if the design principles that led them to where they are were wrong.  

So by mocking `params` and `todo_path`, I'm not just mocking for the sake of mocking.  I'm isolating my tests from the great magnitude of details involved in both methods! :smile:

**Comment by darrencauthon** [comment]
It's one of the reasons I was initially drawn to Ruby.  The ability to be able to quickly fake and manipulate and isolate code, it made testing from something difficult to something very, very, very, very easy.  Ruby has to be the easiest language to test, at least OO-wise... so why don't we take advantage of it? :smile:

**Comment by plicjo** [comment]
Very cool.

I didn't know Ruby was an easy language to test, since I first learned testing in Ruby lol.

Thanks for these PRs. I've had a lot to ponder.

**Pull request closed without merging**
